# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30cfc9dd73da1a11bb51bd9a747b6fa6dc95fc0a5f0b4a1108cd9cf93632cf8e723f9d68ac1ce683e10c81221e9307e039f587c0f430efb05c60594e324a2358

test:
  secret_key_base: 901564db7d6acdf8acb860b8cb43adbfab47f949a2fe065dc777848c55abe2376487526e02dd0fdf316fc864334d30ac0aa29595276d628a9513b6be24abdbf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
